// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages.proto

It has these top-level messages:
	PeerMessage
	HeartBeat
	PeerList
	HoldElection
	Ballot
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// one size fit all message to just use one wire for a peer's message bus
type PeerMessage struct {
	Name             *string       `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	HeartBeat        *HeartBeat    `protobuf:"bytes,2,opt,name=heartBeat" json:"heartBeat,omitempty"`
	PeerList         *PeerList     `protobuf:"bytes,3,opt,name=peerList" json:"peerList,omitempty"`
	HoldElection     *HoldElection `protobuf:"bytes,4,opt,name=holdElection" json:"holdElection,omitempty"`
	Ballot           *Ballot       `protobuf:"bytes,5,opt,name=ballot" json:"ballot,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *PeerMessage) Reset()                    { *m = PeerMessage{} }
func (m *PeerMessage) String() string            { return proto.CompactTextString(m) }
func (*PeerMessage) ProtoMessage()               {}
func (*PeerMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PeerMessage) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *PeerMessage) GetHeartBeat() *HeartBeat {
	if m != nil {
		return m.HeartBeat
	}
	return nil
}

func (m *PeerMessage) GetPeerList() *PeerList {
	if m != nil {
		return m.PeerList
	}
	return nil
}

func (m *PeerMessage) GetHoldElection() *HoldElection {
	if m != nil {
		return m.HoldElection
	}
	return nil
}

func (m *PeerMessage) GetBallot() *Ballot {
	if m != nil {
		return m.Ballot
	}
	return nil
}

type HeartBeat struct {
	CreatedTime      *uint64 `protobuf:"varint,1,req,name=createdTime" json:"createdTime,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HeartBeat) Reset()                    { *m = HeartBeat{} }
func (m *HeartBeat) String() string            { return proto.CompactTextString(m) }
func (*HeartBeat) ProtoMessage()               {}
func (*HeartBeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HeartBeat) GetCreatedTime() uint64 {
	if m != nil && m.CreatedTime != nil {
		return *m.CreatedTime
	}
	return 0
}

type PeerList struct {
	Addresses        []string `protobuf:"bytes,1,rep,name=addresses" json:"addresses,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *PeerList) Reset()                    { *m = PeerList{} }
func (m *PeerList) String() string            { return proto.CompactTextString(m) }
func (*PeerList) ProtoMessage()               {}
func (*PeerList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PeerList) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

type HoldElection struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HoldElection) Reset()                    { *m = HoldElection{} }
func (m *HoldElection) String() string            { return proto.CompactTextString(m) }
func (*HoldElection) ProtoMessage()               {}
func (*HoldElection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Ballot struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Ballot) Reset()                    { *m = Ballot{} }
func (m *Ballot) String() string            { return proto.CompactTextString(m) }
func (*Ballot) ProtoMessage()               {}
func (*Ballot) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Ballot) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*PeerMessage)(nil), "PeerMessage")
	proto.RegisterType((*HeartBeat)(nil), "HeartBeat")
	proto.RegisterType((*PeerList)(nil), "PeerList")
	proto.RegisterType((*HoldElection)(nil), "HoldElection")
	proto.RegisterType((*Ballot)(nil), "Ballot")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 229 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0x49, 0xbb, 0xd6, 0x66, 0xb6, 0xf6, 0x30, 0xa7, 0x1c, 0x0a, 0x86, 0x80, 0x90, 0x8b,
	0x01, 0x7d, 0x84, 0x82, 0xd0, 0x83, 0x42, 0x09, 0xbe, 0x40, 0x6c, 0x06, 0xbb, 0x90, 0x36, 0x25,
	0xc9, 0x33, 0xfa, 0x5c, 0x42, 0xba, 0xdd, 0x5d, 0xc1, 0x5b, 0xf2, 0xfd, 0x1f, 0xcc, 0x3f, 0x03,
	0xeb, 0x13, 0xe5, 0xec, 0xbe, 0x29, 0x9b, 0x4b, 0x8a, 0x25, 0xaa, 0x1f, 0x06, 0xed, 0x9e, 0x28,
	0x7d, 0x5c, 0x31, 0x22, 0x34, 0x67, 0x77, 0x22, 0xc1, 0xe4, 0x4c, 0x73, 0x5b, 0xdf, 0xa8, 0x81,
	0x1f, 0xc9, 0xa5, 0xb2, 0x25, 0x57, 0xc4, 0x4c, 0x32, 0xdd, 0xbe, 0x82, 0xd9, 0xdd, 0x88, 0x1d,
	0x43, 0x7c, 0x82, 0xe5, 0x85, 0x28, 0xbd, 0x77, 0xb9, 0x88, 0x79, 0x15, 0xb9, 0xd9, 0xf7, 0xc0,
	0x0e, 0x11, 0xbe, 0xc0, 0xea, 0x18, 0x83, 0x7f, 0x0b, 0x74, 0x28, 0x5d, 0x3c, 0x8b, 0xa6, 0xaa,
	0x0f, 0x66, 0x37, 0x81, 0xf6, 0x8f, 0x82, 0x8f, 0xb0, 0xf8, 0x72, 0x21, 0xc4, 0x22, 0xee, 0xaa,
	0x7c, 0x6f, 0xb6, 0xf5, 0x6b, 0x7b, 0xac, 0x9e, 0x81, 0x0f, 0x95, 0x50, 0x42, 0x7b, 0x48, 0xe4,
	0x0a, 0xf9, 0xcf, 0xae, 0x5f, 0xa6, 0xb1, 0x53, 0xa4, 0x34, 0x2c, 0x6f, 0xc5, 0x70, 0x03, 0xdc,
	0x79, 0x9f, 0x28, 0x67, 0xca, 0x82, 0xc9, 0xb9, 0xe6, 0x76, 0x04, 0x6a, 0x0d, 0xab, 0x69, 0x2f,
	0xb5, 0x81, 0xc5, 0x75, 0xf4, 0x7f, 0xb7, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xb6, 0x5b,
	0xc2, 0x60, 0x01, 0x00, 0x00,
}
